src/olx/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
     path('products/', include('product.urls',namespace='products')),
       path('', include('accounts.urls',namespace='accounts')),

    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/product/urls.py
from django.urls import path
from .import views

app_name = 'product'
urlpatterns =[
    path('',views.productlist ,name='product_list'),
    path('detail/<slug:product_slug>',views.productdetail, name='product_detail'),
    path('list/<slug:category_slug>',views.productlist, name='product_list_category'),
    path('post-ad/',views.postanad, name='post-ad'),
    path('post-ad/addimages/',views.addimages, name='adimages'),
]

src/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
# Create your models here.

class Product(models.Model):
    CONDITION_TYPE = (
        ("New" , "New"),
        ("Used", "Used")
    )
    ## contains all the product info
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User , on_delete=models.CASCADE)
    description = models.TextField(max_length=500)
    condition = models.CharField(max_length=100, choices=CONDITION_TYPE)
    category = models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    Brand = models.ForeignKey('Brand',on_delete=models.SET_NULL,null=True)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    image = models.ImageField(upload_to='main_product/', blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(blank=True,null=True)
    
    def save(self,*args, **kwargs):
       if not self.slug and self.name :
           self.slug = slugify(self.name)
       super(Product,self).save(*args,**kwargs)
       
             
    def __str__(self):
        #to see product name in admin site
        return self.name
    
class Category(models.Model):
        ##for product category
        
        category_name = models.CharField(max_length=50)
        image = models.ImageField(upload_to='category/',blank=True, null=True)
        slug = models.SlugField(blank=True,null=True)
    
        def save(self,*args, **kwargs):
           if not self.slug and self.category_name :
            self.slug = slugify(self.category_name)
            super(Category,self).save(*args,**kwargs)
       
        class Meta:
            verbose_name = 'category'
            verbose_name_plural = 'categories'
            
        def __str__(self):
        #to see product name in admin site
          return self.category_name
      
class Brand(models.Model):
        ##for product brand
        
        brand_name = models.CharField(max_length=50)
        # image = models.ImageField(upload_to='products/',blank=True, null=True)
        
        class Meta:
            verbose_name = 'brand'
            verbose_name_plural = 'brands'
            
        def __str__(self):
        #to see product name in admin site
          return self.brand_name
      
class ProductImages(models.Model):
        ##for product brand
        product = models.ForeignKey(Product,on_delete=models.CASCADE)
        image = models.ImageField(upload_to='products/',blank=True,null=True)
        
        def __str__(self):
        #to see product name in admin site
          return self.product.name
      
        class Meta:
            verbose_name = 'Product Image'
            verbose_name_plural = 'Product Images'

src/product/forms.py
# import form class from django
from django import forms

# import GeeksModel from models.py
from .models import Product,ProductImages

# create a ModelForm
class ProductForm(forms.ModelForm):
	# specify the name of model to use
	class Meta:
		model = Product
		fields = "__all__"

class ProductImagesForm(forms.ModelForm):
	# specify the name of model to use
	class Meta:
		model = ProductImages
		fields = "__all__"

src/product/views.py
from django.shortcuts import render,redirect
from .models import Product,ProductImages,Category
from django.core.paginator import Paginator
from django.db.models import Count
from django.template import RequestContext
from django.db.models import Q
from .forms import ProductForm,ProductImagesForm

# Create your views here.

def productlist(request , category_slug=None):
    category=None
    # to retrive all products from database
    productlist = Product.objects.all()    
    # print(productlist)
   
    Categorylist = Category.objects.annotate(total_products=Count('product'))
    
    if category_slug :
        category = Category.objects.get(slug=category_slug)
        productlist = productlist.filter(category=category)
        
    search_query = request.GET.get('q')
    if search_query:
      productlist = productlist.filter(
          Q(name__icontains = search_query) |
          Q(description__icontains = search_query) |
          Q(condition__icontains = search_query) |
          Q(Brand__brand_name__icontains = search_query) |
          Q(category__category_name__icontains =search_query)
      )
    
    
    template = 'Product/product_list.html'  
    paginator = Paginator(productlist, 2) # Show 25 contacts per page.
    # paginate_by = 1
    page_number = request.GET.get('page')
    productlist = paginator.get_page(page_number)
    context ={'product_list' : productlist,'category_list': Categorylist,'category':category} 
    return render(request,template,context) 




def productdetail(request,product_slug):
    print(product_slug)
    productdetail = Product.objects.get(slug=product_slug)  
    productimages = ProductImages.objects.filter(product=productdetail)
    
    # print(productlist)

    
    template = 'Product/product_detail.html'  
    context ={'product_details' : productdetail,'product_images' : productimages} 
    return render(request,template,context) 


def postanad(request):
    context ={}
    form = ProductForm(request.POST or None, request.FILES or None)
    template = 'Product/post-ad.html'
    if form.is_valid():
        form.save()
        return  redirect('/products/post-ad/addimages/')
    context['form']= form
    return render(request, template, context)


def addimages(request):
    context ={}
    form = ProductImagesForm(request.POST or None, request.FILES or None)
    template = 'Product/addimages.html'
    if form.is_valid():
        form.save()
        # return render(request,'Product/product_list.html')
    context['form']= form
    return render(request, template, context)

src/product/templates/Product/addimages.html
{% extends 'base2.html' %}
{% load bootstrap4 %}
{% block body %}
	<!-- Submit Ad -->
	<div class="submit-ad main-grid-border">
		<div class="container">
			<h2 class="head">Add images for your ad</h2>
			<form method="post" action="/products/" >
				{% csrf_token %}
				{% buttons %}
				<input type="submit"  value="home">
				{% endbuttons %}	
			</form>                           
			<form method="post" class="form" enctype="multipart/form-data"> 
				{% csrf_token %}
			    {% bootstrap_form form %} 
				{% comment %} {{form}} {% endcomment %}
				{% buttons %}
				<input type="submit" value="post">
				{% endbuttons %}
			</form> 
						</div>
					<div class="clearfix"></div>
						<script src="js/filedrag.js"></script>
				</div>
			</div>
		</div>	
	</div>
{% endblock body %}

src/product/templates/Product/post-ad.html
{% extends 'base2.html' %}
{% load bootstrap4 %}
{% block body %}
	<!-- Submit Ad -->
	<div class="submit-ad main-grid-border">
		<div class="container">
			<h2 class="head">Post an Ad</h2>
                    <form method="post" class="form"  enctype="multipart/form-data"> 
                            {% csrf_token %}
							{% bootstrap_form form %}
                            {% buttons %}
                            <input type="submit"  value="post">
                            {% endbuttons %}
                   </form> 
					{% comment %} <form method="post" class="form" action="addimages/">
						{% csrf_token %}
						
                             <input type="submit" value="addimages">
					</form> {% endcomment %}
						</div>
					<div class="clearfix"></div>
						<script src="js/filedrag.js"></script>
				</div>
			</div>
		</div>	
	</div>
{% endblock body %}

src/product/templates/Product/product_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body%}
	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<li><a href="index.html">Home</a></li>
				<li><a href="{% url 'products:product_list' %}">All Ads</a></li>
				{% comment %} <li class="active"><a href="mobiles.html">Mobiles</a></li> {% endcomment %}
				{% comment %} <li class="active">Mobile Phone</li> {% endcomment %}
			</ol>
			<div class="product-desc">
				<div class="col-md-7 product-view">
					<h2>{{product_details.name}}</h2>
					<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">state</a>, <a href="#">city</a>| Added at {{product_details.created}}, Ad ID: 987654321</p>
					<div class="flexslider">
						<ul class="slides">
							{% for image in product_images %}
							<li data-thumb="{{image.image.url}}">
								<img src="{{image.image.url}}" />
							</li>
							{% endfor %}
						</ul>
					</div>
					
					<!-- FlexSlider -->
					  <script defer src="{% static 'js/jquery.flexslider.js'%}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css'%}" type="text/css" media="screen" />

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4>Brand : <a href="#">{{product_details.Brand}}</a></h4>
						<h4>Views : <strong></strong></h4>
						{% comment %} <p><strong>Display </strong>: 1.5 inch HD LCD Touch Screen</p> {% endcomment %}
						<p><strong>Summary</strong> {{product_details.description}}</p>
					
					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">Rs.{{product_details.price}}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{product_details.condition}}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{product_details.category}}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<h4>
						<h5> want to buy</h5>
						<form method="post" class="form"> 
                            {% csrf_token %}
                            {% buttons %}
                            <input type="submit"  value="buy">
                            {% endbuttons %}
                        </form> 
					</div>
						<div class="tips">
						<h4>Safety Tips for Buyers</h4>
							<ol>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
							</ol>
						</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->
{% endblock body%}

src/product/templates/Product/product_list.html
{% extends 'base.html' %}
{% block body %}
	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">
			<div class="select-box">
				{% comment %} <div class="browse-category ads-list">
					<label>Browse Categories</label>
					<select class="selectpicker show-tick" data-live-search="true">
					  <option data-tokens="Mobiles">All</option>
					  <option data-tokens="Mobiles">Mobiles</option>
					  <option data-tokens="Electronics & Appliances">Electronics & Appliances</option>
					  <option data-tokens="Cars">Cars</option>
					  <option data-tokens="Bikes">Bikes</option>
					  <option data-tokens="Furniture">Furniture</option>
					  <option data-tokens="Pets">Pets</option>
					  <option data-tokens="Books, Sports & Hobbies">Books, Sports & Hobbies</option>
					  <option data-tokens="Fashion">Fashion</option>
					  <option data-tokens="Kids">Kids</option>
					  <option data-tokens="Services">Services</option>
					  <option data-tokens="Jobs">Jobs</option>
					  <option data-tokens="Real Estate">Real Estate</option>
					</select>
				</div> {% endcomment %}
			 <div class="search-product ads-list">
					<label>Search for a specific product</label>
					<div class="search">
						<div id="custom-search-input">
						<div class="input-group">
							<input type="text" class="form-control input-lg" placeholder="Buscar" />
							<span class="input-group-btn">
								<button class="btn btn-info btn-lg" type="button">
									<i class="glyphicon glyphicon-search"></i>
								</button>
							</span>
						</div>
					</div>
					</div>
				</div> 
				<div class="clearfix"></div>
			</div>
			<div class="all-categories">
				<h3> Select your category and find the perfect ad</h3>
				<ul class="all-cat-list">

					{% for category in category_list %}
					  <li><a href="{% url 'products:product_list_category' category.slug %}">{{category}}<span >({{category.total_products}})</a></li>
					{% endfor %}
				</ul>
			</div>
			<ol class="breadcrumb" style="margin-bottom: 5px;">
			  <li><a href="index.html">Home</a></li>
			  <li class="active"><a href="{% url 'products:product_list' %}">All Ads</a></li>
			  {% if category %}
			  <li class="active">{{category}}</li>
			  {% endif %}
			

			</ol>
			<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
					<h3 class="sear-head">Name contains</h3>
					<form method="GET" action="{% url 'products:product_list' %}">
						<input type="text" value="Product name..." name="q" required="">
						<input type="submit" value=" ">
					</form>
				</div>
				

				</div>
				<div class="ads-display col-md-9">
					<div class="wrapper">					
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
												<div id="container">
								
								<div class="sort">
								   <div class="sort-by">
										<label>Sort By : </label>
										<select>
														<option value="">Most recent</option>
														<option value="">Price: Rs Low to High</option>
														<option value="">Price: Rs High to Low</option>
										</select>
									   </div>
									 </div>
								<div class="clearfix"></div>
							<ul class="list">
								{% for product in product_list %}

								<a href="{% url 'products:product_detail' product.slug %}">
									<li>
									<img src={{product.image.url}} title="" alt=""/>
									<section class="list-left">
									<h5 class="title">{{product.name}}</h5>
									<span class="adprice">{{product.price}}</span>
									<p class="catpath">Mobile Phones » {{product.Brand}}</p>
									</section>
									<section class="list-right">
									<span class="date">Date, {{product.created}}</span>
									<span class="cityname">City name</span>
									</section>
									<div class="clearfix"></div>
									</li> 
								</a>
                                {% endfor %}
							</ul>
						</div>
							</div>
						</div>
					
							
						<div class="pagination">
						<ul class="pagination pagination-sm">
							{% comment %} <span class="step-links"> {% endcomment %}
								{% if product_list.has_other_pages %}
								{% if product_list.has_previous %}
            					  <li><a href="?page={{ product_list.previous_page_number }}">&laquo;Prev</a></li>
								{% else %}
								<li class="disabled"></li>
        						{% endif %}
								
						    {% comment %} <span class="current"> {% endcomment %}
								
								{% for page in product_list.paginator.page_range %}
								{% if product_list.number == page %}
								<li><a href="#">{{page}}</a></li>
								{% else %}
							     	<li><a href="?page={{page}}">{{page}}</a></li>
								{% endif %}
							{% comment %} </span>{% endcomment %}
							    {% endfor %}
                            
                      {% if product_list.has_next %}
					  <li><a href="?page={{ product_list.next_page_number }}">Next &raquo;</a></li>
					  {% else %}
						<li class="disabled"></li>
	                  {% endif %}
					  {% endif %}
						</ul>
					</div>
					  </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>	
	</div>
	<!--Products -->
{% endblock body %}